648 add samples for feature assertions of api fluent
robstoll/atrium pull request #1037
Opened 2021-10-29 09:03 UTC by iljakorneckis

Closes #648

I'm a little unsure about naming of the sample methods, so welcome any feedback and will make all required changes asap.
______________________________________
I confirm that I have read the [Contributor Agreements v1.0](https://github.com/robstoll/atrium/blob/main/.github/Contributor%20Agreements%20v1.0.txt), agree to be bound on them and confirm that my contribution is compliant.

2021-11-01 18:00 UTC, iljakorneckis commented
Hey @robstoll, can I bug you for a review?

2021-11-03 07:30 UTC, robstoll requested changes
@iljakorneckis I am sorry, it looks like I forgot to press the submit button (I actually reviewed the same day you submitted :man_facepalming: )

2021-11-03 17:16 UTC, iljakorneckis commented
All good, @robstoll I'll make the changes asap and re-submit

2021-11-05 20:44 UTC, iljakorneckis commented on apis/fluent-en_GB/atrium-api-fluent-en_GB-common/src/test/kotlin/ch/tutteli/atrium/api/fluent/en_GB/samples/FeatureExtractorSamples.kt
> +                .its({ age }) { toEqual(30)} // fails, subject still Person afterwards
Oops! Fixed

2021-11-05 20:46 UTC, merged

2021-11-05 20:47 UTC, robstoll commented
@iljakorneckis thanks for the changes and the contribution as such :tada:

2021-11-05 21:08 UTC, iljakorneckis commented
Uh, @robstoll, I haven't done all the changes requested in the review. Sorry if I was unclear, when I resolved one of them. Should I open a separate PR for the rest?

2021-11-05 21:15 UTC, robstoll commented
@iljakorneckis ah sorry, I figured you don't have time for the rest. I adjusted the last bits myself.

2021-11-05 21:16 UTC, robstoll commented
@iljakorneckis If you should have more time available, then don't hesitate to take a look at other issues :slightly_smiling_face:

2021-11-05 21:24 UTC, iljakorneckis commented
@robstoll Hah, thank you for tackling the rest! I will definitely look at other issues that I can take. Learned a lot about multi-platform Kotlin from this project and started using it myself. :+1:

2021-11-05 21:27 UTC, robstoll commented
@iljakorneckis just be aware of that this project actually uses the old multi-platform plugins (we need to update to the new soonish). If you are interested about the new plugins then take a look at the following issue: #744