migrate AdjustStackSpec from Spek to Kotest
robstoll/atrium pull request #1231
Opened 2022-10-20 02:38 UTC by maxslimb

Migrated the AdjustStackSpec file from Spek to Kotest using Describe Spec.

It Resolves: #1201 
______________________________________
I confirm that I have read the [Contributor Agreements v1.0](https://github.com/robstoll/atrium/blob/main/.github/Contributor%20Agreements%20v1.0.txt), agree to be bound on them and confirm that my contribution is compliant.

2022-10-20 05:27 UTC, robstoll requested changes

2022-10-20 05:27 UTC, robstoll commented on atrium-core/src/jvmTest/kotlin/ch/tutteli/atrium/reporting/erroradjusters/AdjustStackSpec.kt
>  import org.spekframework.spek2.style.specification.describe
Please remove the spek imports

2022-10-20 05:28 UTC, robstoll commented
@maxslimb migrating is quite easy isn't it 🙂
Please also cleanup and remove the spek specifics

2022-10-20 05:38 UTC, maxslimb commented on atrium-core/src/jvmTest/kotlin/ch/tutteli/atrium/reporting/erroradjusters/AdjustStackSpec.kt
>  import org.spekframework.spek2.style.specification.describe
I have done this please review it

2022-10-20 05:48 UTC, robstoll approved these changes

2022-10-27 06:07 UTC, robstoll commented
Take a look at https://github.com/robstoll/atrium/pull/1233/files
In case you want to see what would have been necessary

2022-10-27 06:07 UTC, closed without merging

2022-11-01 18:00 UTC, Dark-Knight11 commented
Sure