Add jvm kotest sample #1325
robstoll/atrium pull request #1530
Opened 2023-08-27 18:07 UTC by ReccaFlames

______________________________________
I confirm that I have read the [Contributor Agreements v1.0](https://github.com/robstoll/atrium/blob/main/.github/Contributor%20Agreements%20v1.0.txt), agree to be bound on them and confirm that my contribution is compliant.

2023-08-29 09:31 UTC, robstoll requested changes

2023-08-29 09:31 UTC, robstoll commented on .github/dependabot.yml
> +  - package-ecosystem: maven
```suggestion
  - package-ecosystem: gradle
```

2023-08-29 15:39 UTC, ReccaFlames commented on samples/jvm/kotest/gradle/wrapper/gradle-wrapper.properties
> +distributionUrl=https\://services.gradle.org/distributions/gradle-7.4.2-bin.zip
Changed to 8.3 based on https://services.gradle.org/distributions/

2023-09-10 06:27 UTC, merged

2023-09-10 06:28 UTC, robstoll commented
@ReccaFlames thanks for your first contribution to Atrium :+1: how about another one?

And don't forget to star Atrium if you like it :slightly_smiling_face: