Solved issue "samples for Iterable.toContain.atLeast"
robstoll/atrium pull request #1585
Opened 2023-10-29 02:24 UTC by fergbaldo

Added atLeast method to IterableLikeToContainCheckerSamples.kt and added @sample annotation to the corresponding function's KDoc in iterableLikeToContainCheckers.kt

CI needs to ensured as passing upon submission of Pull Request

Resolves #1545

______________________________________
I confirm that I have read the [Contributor Agreements v1.0](https://github.com/robstoll/atrium/blob/main/.github/Contributor%20Agreements%20v1.0.txt), agree to be bound on them and confirm that my contribution is compliant.

2023-10-29 13:00 UTC, robstoll requested changes

2023-10-29 13:00 UTC, robstoll commented on apis/fluent/atrium-api-fluent/src/commonTest/kotlin/ch/tutteli/atrium/api/fluent/en_GB/samples/IterableLikeToContainCheckerSamples.kt
> +        fails {
Would be nice if you could explain why it fails
```suggestion
        fails { // because contains only one "A"
```

2023-10-29 13:42 UTC, fergbaldo commented
Hi @robstoll , i'm happy to make these changes and may get a chance tomorrow morning, but I am about to head into some tertiary study exams so it is possible it might be a bit over a week until I can get back to this to add the minor comment changes. Thanks for the review on this and my other two pull requests too!

2023-10-31 09:00 UTC, robstoll commented on apis/fluent/atrium-api-fluent/src/commonTest/kotlin/ch/tutteli/atrium/api/fluent/en_GB/samples/IterableLikeToContainCheckerSamples.kt
> +            expect(listOf("A,B,C")).toContain.inAnyOrder.atLeast(2).entry{
```suggestion
            expect(listOf("A","B","C")).toContain.inAnyOrder.atLeast(2).entry{
```

2023-11-22 21:14 UTC, robstoll commented
@fergbaldo let me know in case you need help

2024-01-20 21:54 UTC, robstoll commented
closing

2024-01-20 21:54 UTC, closed without merging