###Feature/Integrate Custom Random Matrix Generation and Merge Ubuntu and Windows Workflows
robstoll/atrium pull request #1776
Opened 2024-06-12 17:09 UTC by BereKanters

This PR addresses issue #1460 by integrating a custom random matrix generation script and merging the Ubuntu and Windows workflows into a single CI workflow. This change aims to improve test coverage and CI resource efficiency.

- Combined the Ubuntu and Windows workflows into a single ci.yml file.
- Moved common steps, such as caching the Android jar and compiling, into a separate setup job to improve CI efficiency.
- Updated the README file to reflect the new combined CI workflow badge.
______________________________________
I confirm that I have read the [Contributor Agreements v1.0](https://github.com/robstoll/atrium/blob/main/.github/Contributor%20Agreements%20v1.0.txt), agree to be bound on them and confirm that my contribution is compliant.

2024-06-14 21:10 UTC, robstoll requested changes

2024-06-14 21:10 UTC, robstoll commented on .github/workflows/ci.yml
>          uses: actions/checkout@v4
```suggestion
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
```

2024-06-14 21:10 UTC, robstoll commented on .github/workflows/ci.yml
> +      - name: Set up Node.js
no need to setup node, node is installed already for each runner

2024-06-14 21:10 UTC, robstoll commented on .github/workflows/ci.yml
> +    needs: dexer
shouldn't be based on dexer, can be run in parallel to it

2024-06-14 21:11 UTC, robstoll commented on feature-random-matrix-ci.patch
please remove this file again

2024-06-14 21:14 UTC, robstoll requested changes

2024-06-14 21:14 UTC, robstoll commented on .github/workflows/ci.yml
please rename to quality-assurance.yml (and adopt the badges in the readme, I'll leave an example)

2024-06-14 21:14 UTC, robstoll commented on .github/workflows/ci.yml
> +          distribution: 'adopt'
```suggestion
          distribution: ${{ matrix.java_distribution }}
```

2024-06-14 21:15 UTC, robstoll commented on README.md
> +[![Build Status](https://github.com/robstoll/atrium/actions/workflows/ci.yml/badge.svg?event=push&branch=main)](https://github.com/robstoll/atrium/actions?query=workflow%3Aci.yml+branch%3Amain)
```suggestion
[![Quality Assurance](https://github.com/robstoll/atrium/actions/workflows/quality-assurance.yml/badge.svg?event=push&branch=main)](https://github.com/robstoll/atrium/actions/workflows/quality-assurance.yml?query=branch%3Amain)
```

2024-06-14 21:18 UTC, robstoll commented on .github/workflows/ci.yml
Don't forget to remove the build-ubuntu.yml and build-windows.yml in the end

2024-06-15 20:51 UTC, robstoll commented on .github/workflows/quality-assurance.yml
> +    needs: []  #Not sure if it should be left empty or if it should contain generate-matrix
if you would want to use different OS etc. then you would need it. IMO good enough if we use jdk17 and adopt only for now

2024-06-15 20:51 UTC, robstoll commented on .github/workflows/quality-assurance.yml
> +          distribution: ${{ matrix.java_distribution }}
keep adopt and 17 we define the matrix differently in this job (i.e. we only define `kotlin_version`, see further above)

2024-06-15 20:54 UTC, robstoll commented on .github/workflows/quality-assurance.yml
> +          fetch-depth: 1
I think codecov needs the history to work correctly, remove here again (but keep the others)

2024-06-15 20:54 UTC, robstoll commented on .github/workflows/quality-assurance.yml
> +          fetch-depth: 1
good idea, we also don't need the history for the dexer job :+1:

2024-06-16 06:12 UTC, robstoll reviewed
You have merge conflicts which means you need to rebase on main of Atrium, i.e. not on your local main -- add atrium as `git remote add upstream https://github.com/robstoll/atrium` and then `git rebase upstream/main` and resolve the conflicts. Let me know in case you need help with it

2024-06-16 06:12 UTC, robstoll commented on .github/workflows/quality-assurance.yml
> +    needs: []
You could also remove the line entirely

2024-06-16 12:38 UTC, BereKanters commented
I have no clue what just happend, I did git rebase upstream/main (I already had the upstream set) afterwords asked me to resolve conflicts where I removed the build_windows file by using: 'git rm .github/workflows/build-windows.yml ' then added `git add .github/workflows/quality-assurance.yml` did `git rebase --continue ` and then pushed but it seems it pushed all of that with it for some reason.

2024-06-16 12:50 UTC, BereKanters commented
Alright I went back to an older commit [28ff511] and it should now be fixed.

2024-06-16 13:48 UTC, robstoll commented on .github/workflows/matrix.js
> +matrix.addAxis({
You also need to add an axis for distribution. I suggest you use:
'corretto',
		'liberica',
		'microsoft',
		'temurin',
		'zulu',

2024-06-16 14:39 UTC, robstoll submitted a review, later dismissed

2024-06-16 14:42 UTC, merged

2024-06-16 14:45 UTC, robstoll commented
@BereKanters thanks for your second contribution. I missed that you changed the target branch just before I merged. We'll figure out if everything was as intended at a screen bigger than my mobile phone.