samples for Iterable.toContain....entries
robstoll/atrium pull request #1815
Opened 2024-08-15 15:17 UTC by hubtanaka

Issue #1553 

_api-fluent_

- [x] add a entries method in IterableLikeToContainInAnyOrderCreatorSamples for Iterable.toContain.inAnyOrder.entries(...)
- [x] add a entries method in IterableLikeToContainInAnyOrderOnlyCreatorSamples for Iterable.toContain.inAnyOrder.only.entries(...)
- [x] add a entries method in IterableLikeToContainInOrderOnlyCreatorSamples for Iterable.toContain.inOrder.only.entries(...
- [x] link in the KDoc of the corresponding function in iterableLikeToContain...Creators.kt to the samples via @sample (see charSequenceToContainCreators.kt)
______________________________________
I confirm that I have read the [Contributor Agreements v1.0](https://github.com/robstoll/atrium/blob/main/.github/Contributor%20Agreements%20v1.0.txt), agree to be bound on them and confirm that my contribution is compliant.

2024-08-15 15:57 UTC, robstoll requested changes
some suggestions for improvement.
Please fix at least the typo `an "D"` => `a "D"`

2024-08-15 15:57 UTC, robstoll commented on apis/fluent/atrium-api-fluent/src/commonTest/kotlin/ch/tutteli/atrium/api/fluent/en_GB/samples/IterableLikeToContainInAnyOrderCreatorSamples.kt
> +            null, null, null
```suggestion
            null
```

2024-08-15 15:57 UTC, robstoll commented on apis/fluent/atrium-api-fluent/src/commonTest/kotlin/ch/tutteli/atrium/api/fluent/en_GB/samples/IterableLikeToContainInAnyOrderOnlyCreatorSamples.kt
> +        fails { // because the List does not contain an "D" that is in entries
```suggestion
        fails { // because the List does not contain a "D"
```

2024-08-15 15:57 UTC, robstoll commented on apis/fluent/atrium-api-fluent/src/commonTest/kotlin/ch/tutteli/atrium/api/fluent/en_GB/samples/IterableLikeToContainInAnyOrderOnlyCreatorSamples.kt
> +        fails { // because the List contains an "A" that is not in entries
```suggestion
        fails { // because the List contains additionally an "A" (not covered in entries)
```

2024-08-15 15:57 UTC, robstoll commented on apis/fluent/atrium-api-fluent/src/commonTest/kotlin/ch/tutteli/atrium/api/fluent/en_GB/samples/IterableLikeToContainInAnyOrderOnlyCreatorSamples.kt
> +        fails { // because the List does not contain a null that is in entries
```suggestion
        fails { // because the List does not contain a null
```

2024-08-15 15:57 UTC, robstoll commented on apis/fluent/atrium-api-fluent/src/commonTest/kotlin/ch/tutteli/atrium/api/fluent/en_GB/samples/IterableLikeToContainInOrderOnlyCreatorSamples.kt
> +        fails { // because the List contains an "A" that is not in entries
```suggestion
        fails { // because the List contains an additional "A" at the beginning
```

2024-08-15 15:57 UTC, robstoll commented on apis/fluent/atrium-api-fluent/src/commonTest/kotlin/ch/tutteli/atrium/api/fluent/en_GB/samples/IterableLikeToContainInOrderOnlyCreatorSamples.kt
> +        fails { // because the List does not contain an "D" that is in entries
```suggestion
        fails { // because the List does not contain a "D" at the end
```

2024-08-15 15:57 UTC, robstoll commented on apis/fluent/atrium-api-fluent/src/commonTest/kotlin/ch/tutteli/atrium/api/fluent/en_GB/samples/IterableLikeToContainInOrderOnlyCreatorSamples.kt
> +        fails { // because the List does not contain a null that is in entries
```suggestion
        fails { // because the List contains a "C" and not null at the end
```

2024-08-15 23:27 UTC, hubtanaka commented
@robstoll thanks for your suggestions.  I committed all of them.

2024-08-16 13:06 UTC, robstoll approved these changes

2024-08-16 13:06 UTC, merged

2024-08-16 13:06 UTC, robstoll commented
@hubtanaka thanks 🙂👍