Update Gradle wrapper to 6.7
robstoll/atrium pull request #639
Opened 2020-10-18 21:55 UTC by fejd

Update the Gradle wrapper used by the root and sample
projects from 6.3 to 6.7.

______________________________________
I confirm that I have read the [Contributor Agreements v1.0](https://github.com/robstoll/atrium/blob/master/.github/Contributor%20Agreements%20v1.0.txt), agree to be bound on them and confirm that my contribution is compliant.

2020-10-19 05:04 UTC, robstoll commented
@fejd I guess you have updated the number manually. Use the utility from gradle itself to update the wrapper. At least the jar should change as well.

2020-10-19 18:10 UTC, fejd commented
Ah sorry, yes that's how I've done in the past. I'll use `./gradlew wrapper --gradle-version 6.7` instead, and map the distribution type to what's currently in the individual properties files. Not part of this commit but should all projects use the same distribution type, either -bin or -all? I also noticed that the update utility prefers Windows style carriage returns (`^M`) in the .bat files, but the existing files use Linux/Unix line endings. I'll fix that with `dos2unix` to make the change easier to review, but I could make a subsequent commit to fix that if you want. It'd make future upgrades a bit smoother I think.

2020-10-19 18:18 UTC, robstoll commented
> but the existing files use Linux/Unix line endings.

maybe worth adding a .gitattributes file declaring clrf for bat files?

Fine for me if you do everything in one commit but two commits are also good. What you think is better :)

2020-10-21 06:14 UTC, robstoll requested changes

2020-10-21 06:14 UTC, robstoll commented on atrium-scala/gradlew.bat
> +@rem
I'm sorry, this just changed in master (atrium-scala was renamed to atrium-scala2).
Please rebase your changes on master and re-do the update in atrium-scala2

btw. nice that you have spotted this, forgot to include it in the description :+1:

2020-10-21 06:17 UTC, robstoll commented on samples/maven/.gitattributes
> -#
Can you please keep these files in the samples and copy it to the root.
The samples are independent projects where the idea is that you as a user can copy this as a starting point of a new project.

2020-10-22 20:07 UTC, closed without merging