add convenience shortcut for `Path.toBeASymbolicLink` feature
robstoll/atrium pull request #811
Opened 2021-02-14 10:59 UTC by fimbulwint

For both infix and fluent API styles

______________________________________
I confirm that I have read the [Contributor Agreements v1.0](https://github.com/robstoll/atrium/blob/master/.github/Contributor%20Agreements%20v1.0.txt), agree to be bound on them and confirm that my contribution is compliant.

2021-02-14 14:27 UTC, robstoll requested changes
@fimbulwint thanks for your first contribution. A few improvements and we are good to merge it

2021-02-14 14:27 UTC, robstoll commented on apis/fluent-en_GB/atrium-api-fluent-en_GB-jvm/src/test/kotlin/ch/tutteli/atrium/api/fluent/en_GB/samples/PathAssertionSamples.kt
> +        // Fails, as subject `path` is a not a symbolic link
It's correct but I think the example would be better if the file actually exists. I suggest you create a regular file at that place

2021-02-14 14:27 UTC, robstoll commented on apis/infix-en_GB/atrium-api-infix-en_GB-jvm/src/test/kotlin/ch/tutteli/atrium/api/infix/en_GB/samples/PathAssertionSamples.kt
> +        // Fails, as subject `path` is a not a symbolic link
Same same as for fluent

2021-02-14 14:27 UTC, robstoll commented on logic/atrium-logic-jvm/src/main/kotlin/ch/tutteli/atrium/logic/impl/DefaultPathAssertions.kt
> +        changeSubjectToFileAttributes(container, NOFOLLOW_LINKS) { fileAttributesExpect ->
I see that you copied the code of fileTypeAssertion due to the NOFOLLOW_LINKS.I suggest you add `linkOption: LinkOption? = null` to fileTypeAssertion instead

2021-02-14 14:27 UTC, robstoll commented on misc/specs/atrium-specs-jvm/src/main/kotlin/ch/tutteli/atrium/specs/integration/PathExpectationsSpec.kt
> +            val link = Files.createSymbolicLink(tempFolder.resolve("link"), target)
```suggestion
            val link = tempFolder.newSymbolicLink("link", target)
```

2021-02-20 18:48 UTC, robstoll approved these changes

2021-02-20 18:49 UTC, merged

2021-02-20 18:50 UTC, robstoll commented
@fimbulwint thanks for your first contribution :slightly_smiling_face: :+1: 

We could use your help for other issues, and don't forget to :star: Atrium:
https://github.com/robstoll/atrium/issues?q=is%3Aissue+is%3Aopen+label%3A%22help+wanted%22

2021-02-20 18:57 UTC, fimbulwint commented
@robstoll happy to contribute :slightly_smiling_face:

I'll take a look at some other issue when I get the chance.